### ISSUE TITLE
Unable to uninstall, get an error

### ISSUE THREAD

**Issue by lapagept** [Vauxoo/addons-vauxoo#115]
Odoo 8.0, trying to install stock_picking_cancel

Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/openerp/http.py", line 525, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/openerp/http.py", line 562, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo/openerp/http.py", line 302, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/openerp/http.py", line 299, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoo/openerp/http.py", line 791, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo/openerp/http.py", line 395, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo/openerp/modules/registry.py", line 346, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/openerp/modules/loading.py", line 363, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/openerp/modules/loading.py", line 158, in load_module_graph
    models = registry.load(cr, package)
  File "/home/odoo/openerp/modules/registry.py", line 148, in load
    model = cls._build_model(self, cr)
  File "/home/odoo/openerp/models.py", line 595, in _build_model
    original_module = pool[name]._original_module if name in parents else cls._module
  File "/home/odoo/openerp/modules/registry.py", line 101, in __getitem__
    return self.models[model_name]
KeyError: 'stock.picking.in'

**Comment by zaoral** [comment]
Hello @lapagept 
Thanks for report this issue.

A fast review show me that there is problem with the migration of the module since the stock.picking.in model do not exist anymore at the odoo version 8.0.

The stock.picking.in and stock.picking.out models were merge into the stock.picking model. The changes needed to resolve this bug is to remove the references to this models and unify the needed features to the stock.picking model.

You can contribute doing this fix or if not we will attend this issue when we can.
Please let us now via this issue if you decide either you want to contribute or you dont.

Regards.

**Comment by yasminmustafa** [comment]
I have the same problem and i need a solution please

**Comment by nhomar** [comment]
@yasminmustafa 

Can you share the sha of the repository you are using? I think you should update it, it is solved since some thime ago.

**Comment by yasminmustafa** [comment]
Hi
I am using odoo version 8
and when install it from odoo apps version 8 it give me error in stock
picking in and i update it many times it give me server error
and to solve it i delete it from ssh
is there any solution please
thanks

On 22 August 2015 at 21:11, Nhomar Hernández [Vauxoo] <
notifications@github.com> wrote:

> @yasminmustafa https://github.com/yasminmustafa
> 
> Can you share the sha of the repository you are using? I think you should
> update it, it is solved since some thime ago.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Vauxoo/addons-vauxoo/issues/115#issuecomment-133736569
> .

## 

---

_Tip_:  http://goo.gl/jV6izOEdit Microsoft http://goo.gl/jV6izO® Office 
http://goo.gl/jV6izO® documents without installing Office 

## http://goo.gl/jV6izO

**Comment by nhomar** [comment]
@zaoral can you make a local test in order to verify if it is solved and close the issue.

Regards.
