### ISSUE TITLE
Unable to install stock_shipping_packaging on V8

### ISSUE THREAD

**Issue by mboldireff** [Vauxoo/addons-vauxoo#173]
Hi Nomar,

We have an issue when trying to install the stock_shipping_packaging on V8 :

Traceback (most recent call last):
  File "/home/mboldireff/odoo/test/git/odoo/openerp/http.py", line 508, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/http.py", line 526, in dispatch
    result = self._call_function(*_self.params)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/http.py", line 285, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/http.py", line 282, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/http.py", line 742, in __call__
    return self.method(_args, *_kw)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/http.py", line 378, in response_wrap
    response = f(_args, *_kw)
  File "/home/mboldireff/odoo/test/git/odoo/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/mboldireff/odoo/test/git/odoo/addons/web/controllers/main.py", line 932, in _call_kw
    records = getattr(request.session.model(model), method)(_args, *_kwargs)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/http.py", line 844, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/models.py", line 3078, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/models.py", line 3110, in read
    self._read_from_database(stored)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/models.py", line 3274, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/osv/fields.py", line 1356, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/mboldireff/odoo/test/git/odoo/openerp/addons/base/module/module.py", line 174, in _get_desc
    html = lxml.html.document_fromstring(doc)
  File "/home/mboldireff/odoo/test/git/sfl/tools/eggs/lxml-3.4.2-py2.7-linux-x86_64.egg/lxml/html/__init__.py", line 613, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 3094, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70505)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106339)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105130)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99812)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94286)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95722)
  File "parser.pxi", line 631, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95001)
XMLSyntaxError: None

Thanks in advance for your help.

Regards,

Mat (Savoir-faire Linux)

**Comment by nhomar** [comment]
Hello @mboldireff 

Thanks for point us out this issue, we plan migrate our modules just when customer which asked for it asked us to migrate them.

In this particular case I will ask to @yaniaular to answer why this module was developed and if it applies for V8.0

Reading the description it does something like what "operations" model is doing now Out of the Box in V8.0 then probably it will be deprecated.

Regards.

**Comment by yaniaular** [comment]
Hello @nhomar, the error is for a index.html file in the path static/description/index.html that it is unnecessary.

The module is not migrated in version 8.0.

Its function is add a ean code in module for packaging, in addition to a workflow for confirm that the pack is ready and the code ean is validated.

However, this module (stock_shipping_packaging) is not required on version 8.0 by the <a href="https://www.odoo.com/es_ES/forum/how-to/warehouse-management-6/whats-the-difference-between-quants-lots-and-products-55243">theme of quants</a>  (More information: <a href="https://www.youtube.com/watch?v=kYayZWDKPJ0">Odoo 8.0 : Purchase and Warehouse Demonstration</a> and <a href="http://www.slideshare.net/openobject/odoo-warehouse-management">odoo-warehouse-management</a>), since the main objective of this module was a way to label/group packages in the model stock.tracking (model depreciated in Odoo) ... Then, actually in odoo, with the relationship you have with the quants, stock.moves and pickings. You can get the result you want, plus you can use Lots numbers.

**Comment by mboldireff** [comment]
Hi @yaniaular 

I have tried it in the V.7 and thit is the message I got

Odoo

Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 518, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 539, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 295, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 292, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 755, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 388, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/src/custom/private/loempia/controllers/legacy.py", line 54, in wrapper
    return fn(self, **kw)
  File "/home/odoo/src/custom/private/loempia/controllers/legacy.py", line 104, in call_kw
    return super(Legacy70DataSet, self).call_kw(**kw)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 388, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo/src/odoo/8.0/addons/web/controllers/main.py", line 949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/8.0/addons/web/controllers/main.py", line 932, in _call_kw
    records = getattr(request.session.model(model), method)(_args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/http.py", line 859, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 3083, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 3126, in read
    values[name] = field.convert_to_read(record[name], use_name_get)
  File "/home/odoo/src/odoo/8.0/openerp/models.py", line 5492, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/8.0/openerp/fields.py", line 774, in **get**
    self.determine_value(record)
  File "/home/odoo/src/odoo/8.0/openerp/fields.py", line 876, in determine_value
    self.compute_value(recs)
  File "/home/odoo/src/odoo/8.0/openerp/fields.py", line 832, in compute_value
    self._compute_value(records)
  File "/home/odoo/src/odoo/8.0/openerp/fields.py", line 824, in _compute_value
    self.compute(records)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/api.py", line 395, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/home/odoo/src/custom/private/loempia/loempia2.py", line 307, in _get_desc
    html = lxml.html.document_fromstring(doc)
  File "/usr/lib/python2.7/dist-packages/lxml/html/__init__.py", line 532, in document_fromstring
    value = etree.fromstring(html, parser, **kw)
  File "lxml.etree.pyx", line 2756, in lxml.etree.fromstring (src/lxml/lxml.etree.c:54726)
  File "parser.pxi", line 1578, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:82843)
  File "parser.pxi", line 1457, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:81641)
  File "parser.pxi", line 965, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:78311)
  File "parser.pxi", line 569, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:74567)
  File "parser.pxi", line 650, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:75458)
  File "parser.pxi", line 599, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:74922)
XMLSyntaxError: line 37: Unexpected end tag : p

----- Original Message -----

**Comment by nhomar** [comment]
Hello we redo all index.html files.

Can you confirm us all is Ok now? I will close this in favor of the commit #5a633efb5a

If you have more issue sqwith this module let us know.

thanks for the information.

Regards.
