### ISSUE TITLE
ProgrammingError: relation "account_invoice_report" does not exist

### ISSUE THREAD

**Issue by DigitalMenes** [Vauxoo/addons-vauxoo#339]
Hi, to report problem that I have

Impacted versions:
- Odoo 8.0-20150703
  -  Ubuntu server 14.04

Steps to reproduce:
1. Installed module Invoice Date Time
2. Invoice shows date and time now
3. Click on sales error shows
4. Cannot add new clients or see old ones
5. Unistalling module and reinstalling sales module fixes problem

Current behavior:
- Invoice shows date and time but sales module does not work

Expected behavior:
- Sales module should work and date and time on invoice should be on invoice

Error:

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 884, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 905, in do_search_read
    request.context)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 908, in proxy
    result = meth(cr, request.uid, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5144, in search_read
    result = self.read(cr, uid, record_ids, fields, context=read_ctx)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3139, in read
    result = BaseModel.read(records, fields, load=load)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3174, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 3352, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/usr/lib/python2.7/dist-packages/openerp/osv/fields.py", line 1466, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/sale/sales_team.py", line 39, in _get_invoices_data
    values = self.__get_bar_values(cr, uid, obj, created_domain, ['price_total', 'date'], 'price_total', 'date', context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/sales_team/sales_team.py", line 58, in __get_bar_values
    group_obj = obj.read_group(cr, uid, domain, read_fields, groupby_field, context=context)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 2140, in read_group
    cr.execute(query, where_clause_params)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 158, in wrapper
    return f(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "account_invoice_report" does not exist
LINE 3:             FROM "account_invoice_report"
                         ^

How to fix this?

Thanks

**Comment by hbto** [comment]
Hi @mehnihma 

Try to follow these guidelines when posting any issue or PR

https://github.com/odoo/odoo/wiki/Contributing

Best Regards.

**Comment by mehnihma** [comment]
I have entered all information?

**Comment by zaoral** [comment]
Hello @mehnihma please indicate the information indicate in
https://github.com/odoo/odoo/wiki/Contributing to report your bug. 
You need to introduce more information,
Please use this template to add the information of your issue.

```
**Quantity field is ignored in a sale order**

Impacted versions:

 - 8.0

Steps to reproduce:

 1. create a new sale order
 2. add a line with product 'Service', quantity 2, unit price 10.0
 3. validate the sale order

Current behavior:

 - Total price of 10.0

Expected behavior:

 - Total price of 20.0 (2 * 10 = 20)
```

**Comment by DigitalMenes** [comment]
Updated information
