### ISSUE TITLE
[8.0] website_product_availability: The model location.quants has no access rules

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/addons-vauxoo#406]
CI-log of customer that use this module:

``` logger
2015-08-08 07:27:18,980 240 [1;32m[1;49mINFO[0m openerp_test openerp.tests.common: phantomjs: Tour 'shop_buy_product' Step: 'select ipod' (906ms)
2015-08-08 07:27:19,393 240 [1;33m[1;49mWARNING[0m openerp_test openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: location.quants
2015-08-08 07:27:19,408 240 [1;33m[1;49mWARNING[0m openerp_test openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 4, model: location.quants
2015-08-08 07:27:19,414 240 [1;33m[1;49mWARNING[0m openerp_test openerp.addons.website.models.ir_http: 403 Forbidden:

Traceback (most recent call last):
  File "/root/odoo-8.0/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_http.py", line 147, in _handle_exception
    return request._handle_exception(exception)
  File "/root/odoo-8.0/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/root/odoo-8.0/openerp/http.py", line 1368, in get_response
    result.flatten()
  File "/root/odoo-8.0/openerp/http.py", line 1241, in flatten
    self.response.append(self.render())
  File "/root/odoo-8.0/openerp/http.py", line 1235, in render
    context=request.context)
  File "/root/odoo-8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/root/odoo-8.0/addons/website/models/ir_ui_view.py", line 172, in render
    return super(view, self).render(cr, uid, id_or_xml_id, values=values, engine=engine, context=context)
  File "/root/odoo-8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_ui_view.py", line 1026, in render
    return self.pool[engine].render(cr, uid, id_or_xml_id, qcontext, loader=loader, context=context)
  File "/root/odoo-8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 261, in render
    return self.render_node(self.get_template(id_or_xml_id, qwebcontext), qwebcontext)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 298, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 436, in render_tag_call
    d[0] = self.render_element(element, template_attributes, generated_attributes, d)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 300, in render_node
    result = self.render_element(element, template_attributes, generated_attributes, qwebcontext)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 321, in render_element
    g_inner.append(self.render_node(current_node, qwebcontext))
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 298, in render_node
    result = self._render_tag[t_render](self, element, template_attributes, generated_attributes, qwebcontext)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 430, in render_tag_if
    if self.eval_bool(template_attributes["if"], qwebcontext):
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 236, in eval_bool
    return int(bool(self.eval(expr, qwebcontext)))
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 205, in eval
    raise_qweb_exception(message="Could not evaluate expression %r" % expr, expression=expr, template=template)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 202, in eval
    return qwebcontext.safe_eval(expr)
  File "/root/odoo-8.0/openerp/addons/base/ir/ir_qweb.py", line 88, in safe_eval
    return eval(expr, None, locals_dict, nocopy=True, locals_builtins=True)
  File "/root/odoo-8.0/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/root/odoo-8.0/openerp/fields.py", line 823, in __get__
    return record._cache[self]
  File "/root/odoo-8.0/openerp/models.py", line 5933, in __getitem__
    return value.get() if isinstance(value, SpecialValue) else value
  File "/root/odoo-8.0/openerp/fields.py", line 55, in get
    raise self.exception
QWebException: ('AccessError', u'Sorry, you are not allowed to access this document. Please contact your system administrator if you think this is an error.\n\n(Document model: location.quants)')

2015-08-08 07:27:19,498 240 [1;32m[1;49mINFO[0m openerp_test werkzeug: 127.0.0.1 - - [08/Aug/2015 07:27:19] "GET /shop/product/ipod-13 HTTP/1.1" 403 -
...
2015-08-08 07:26:27,020 240 [1;33m[1;49mWARNING[0m openerp_test openerp.modules.loading: The model location.quants has no access rules, consider adding one. E.g. access_location_quants,access_location_quants,model_location_quants,,1,0,0,0
```

**Comment by oscarolar** [comment]
@hugho-ad  dude, can you help me with this?
