### ISSUE TITLE
warehouse_interim_receipt: test is failling 

### ISSUE THREAD

**Issue by oscarolar** [Vauxoo/addons-vauxoo#514]
```
2015-11-02 03:40:54,662 213 INFO openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: ======================================================================
2015-11-02 03:40:54,662 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: ERROR: test_04 (openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt.TestWarehouseReceipt)
2015-11-02 03:40:54,662 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: ` Wizard Warehouse Receipt Input
2015-11-02 03:40:54,662 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: Traceback (most recent call last):
2015-11-02 03:40:54,662 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/build/Vauxoo/yoytec/warehouse_interim_receipt/tests/test_warehouse_receipt.py", line 192, in test_04
2015-11-02 03:40:54,662 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     order = self.create_po_and_validate()
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/build/Vauxoo/yoytec/warehouse_interim_receipt/tests/test_warehouse_receipt.py", line 160, in create_po_and_validate
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     self.create_pol(order, self.product)
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/build/Vauxoo/yoytec/warehouse_interim_receipt/tests/test_warehouse_receipt.py", line 180, in create_pol
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     'date_planned': time.strftime('%Y-%m-%d')
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/openerp/api.py", line 239, in wrapper
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     return new_api(self, *args, **kwargs)
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/openerp/api.py", line 547, in new_api
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     result = method(self._model, cr, uid, self.ids, *args, **kwargs)
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/addons/mail/mail_thread.py", line 432, in write
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/openerp/api.py", line 241, in wrapper
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     return old_api(self, *args, **kwargs)
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/openerp/api.py", line 363, in old_api
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     result = method(recs, *args, **kwargs)
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/openerp/models.py", line 3778, in write
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     self._write(old_vals)
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/openerp/api.py", line 239, in wrapper
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     return new_api(self, *args, **kwargs)
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/openerp/api.py", line 547, in new_api
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     result = method(self._model, cr, uid, self.ids, *args, **kwargs)
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/openerp/models.py", line 3949, in _write
2015-11-02 03:40:54,663 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     recs._validate_fields(vals)
2015-11-02 03:40:54,664 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/openerp/api.py", line 239, in wrapper
2015-11-02 03:40:54,664 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     return new_api(self, *args, **kwargs)
2015-11-02 03:40:54,664 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/openerp/models.py", line 1277, in _validate_fields
2015-11-02 03:40:54,664 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     check(self)
2015-11-02 03:40:54,664 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/openerp/api.py", line 239, in wrapper
2015-11-02 03:40:54,664 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     return new_api(self, *args, **kwargs)
2015-11-02 03:40:54,664 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/odoo-8.0/openerp/api.py", line 398, in new_api
2015-11-02 03:40:54,664 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     result = [method(rec, *args, **kwargs) for rec in self]
2015-11-02 03:40:54,664 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `   File "/root/addons-vauxoo/purchase_order_line_sequence/model/purchase.py", line 47, in _check_order_lines_sequence
2015-11-02 03:40:54,664 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: `     str(sequences))
2015-11-02 03:40:54,664 213 ERROR openerp_test openerp.addons.warehouse_interim_receipt.tests.test_warehouse_receipt: ` ValidationError: ('ValidateError', 'The sequence must be unique per purchase order!.\nThe next sequence numbers are already used:\n[1]')
```

**Comment by oscarolar** [comment]
@zaoral I dont know if this a known error, tested in runbot.

**Comment by oscarolar** [comment]
Previous thread here: https://github.com/Vauxoo/yoytec/issues/266

**Comment by moylop260** [comment]
Fixed if you create a `purchase_order_line` you need add a context with `'order_line': order.order_line` to work fine with `purchase_order_line_sequence` module.

``` python
order.with_context({
            'order_line': order.order_line
        }).write({
            'order_line': [(0, 0, {
                'product_id': product.id,
                ...
            })]})
```

**Comment by moylop260** [comment]
@oscarolar 
qp2w

**Comment by moylop260** [comment]
@oscarolar 
qp2w2
