### ISSUE TITLE
[8.0] user_story: "AssertionError: [] is not True : The message was not created"

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/addons-vauxoo#535]
In build 8.0 of [instance](https://magnum.travis-ci.com/Vauxoo/instance/jobs/25249245#L1049-L1050) of runbot show next traceback

``` bash
2015-11-18 15:46:21,479 117 ERROR openerp_test openerp.addons.user_story.tests.test_user_story: FAIL
2015-11-18 15:46:21,480 117 INFO openerp_test openerp.addons.user_story.tests.test_user_story: test_approve_button (openerp.addons.user_story.tests.test_user_story.TestUserStory)
2015-11-18 15:46:22,672 117 INFO openerp_test openerp.addons.user_story.tests.test_user_story: test_copy_method (openerp.addons.user_story.tests.test_user_story.TestUserStory)
2015-11-18 15:46:23,667 117 INFO openerp_test openerp.addons.user_story.tests.test_user_story: test_create_method (openerp.addons.user_story.tests.test_user_story.TestUserStory)
2015-11-18 15:46:24,509 117 INFO openerp_test openerp.addons.user_story.tests.test_user_story: test_unlink_method (openerp.addons.user_story.tests.test_user_story.TestUserStory)
2015-11-18 15:46:25,524 117 INFO openerp_test openerp.addons.user_story.tests.test_user_story: test_write_method (openerp.addons.user_story.tests.test_user_story.TestUserStory)
2015-11-18 15:46:26,517 117 INFO openerp_test openerp.addons.user_story.tests.test_user_story: ======================================================================
2015-11-18 15:46:26,518 117 ERROR openerp_test openerp.addons.user_story.tests.test_user_story: FAIL: test_acceptability_criterial_buttons (openerp.addons.user_story.tests.test_user_story.TestUserStory)
2015-11-18 15:46:26,518 117 ERROR openerp_test openerp.addons.user_story.tests.test_user_story: Traceback (most recent call last):
2015-11-18 15:46:26,518 117 ERROR openerp_test openerp.addons.user_story.tests.test_user_story: `   File "/root/odoo-8.0/openerp/tools/misc.py", line 1139, in deco
2015-11-18 15:46:26,518 117 ERROR openerp_test openerp.addons.user_story.tests.test_user_story: `     return func(*args, **kwargs)
2015-11-18 15:46:26,518 117 ERROR openerp_test openerp.addons.user_story.tests.test_user_story: `   File "/root/addons-vauxoo/user_story/tests/test_user_story.py", line 251, in test_acceptability_criterial_buttons
2015-11-18 15:46:26,518 117 ERROR openerp_test openerp.addons.user_story.tests.test_user_story: `     self.assertTrue(m_id, "The message was not created")
2015-11-18 15:46:26,518 117 ERROR openerp_test openerp.addons.user_story.tests.test_user_story: ` AssertionError: [] is not True : The message was not created
2015-11-18 15:46:26,518 117 INFO openerp_test openerp.addons.user_story.tests.test_user_story: Ran 6 tests in 6.949s
2015-11-18 15:46:26,519 117 ERROR openerp_test openerp.addons.user_story.tests.test_user_story: FAILED
2015-11-18 15:46:26,519 117 INFO openerp_test openerp.addons.user_story.tests.test_user_story:  (failures=1)
2015-11-18 15:46:26,519 117 INFO openerp_test openerp.modules.module: openerp.addons.user_story.tests.test_user_story tested in 6.95s, 5221 queries
2015-11-18 15:46:26,519 117 ERROR openerp_test openerp.modules.module: Module user_story: 1 failures, 0 errors
```

**Comment by moylop260** [comment]
@zaoral 
Could you help us to fix in a opportunity?

**Comment by zaoral** [comment]
Hi @moylop260. Reviewing this Issue in what instance you this error appears?

**Comment by moylop260** [comment]
[instance](https://magnum.travis-ci.com/Vauxoo/instance/jobs/25249245#L1049-L1050)

**Comment by zaoral** [comment]
oh. the instance named istanced. ok. My bad @moylop260 
It shows like the message after approve a criteria is not been created.
I will check this functional

**Comment by zaoral** [comment]
@moylop260 the error was in the test context. The unit test case was trying to find the generate message by compare if it find a spanish string. this string is in english in the original message. the test was updated and now the test pass (at local)

I create a new dummy PR in Vauxoo/instance to check if this is really fixed.

Best Regards.
