### ISSUE TITLE
account_voucher_no_check_default NotImplementedError: '__setitem__' not supported on frozendict

### ISSUE THREAD

**Issue by AizenL** [Vauxoo/addons-vauxoo#773]
Odoo Version: 8.0
Module: account_voucher_no_check_default
Module version: 8.0.1.6

Steps to reproduce: 
1.- Install Module
2. Go to Customer Payments 
3. Create.

ERROR:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\http.py", line 539, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\http.py", line 576, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\http.py", line 312, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\service\model.py", line 118, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\http.py", line 309, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\http.py", line 805, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\http.py", line 405, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\openerp\addons\web\controllers\main.py", line 944, in call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\openerp\addons\web\controllers\main.py", line 936, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\api.py", line 399, in old_api
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\models.py", line 5956, in onchange
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\models.py", line 5863, in _onchange_eval
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\openerp\addons\account_voucher_no_check_default\account_voucher.py", line 103, in onchange_partner_id
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\api.py", line 268, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\openerp\addons\account_voucher_no_check_default\account_voucher.py", line 74, in recompute_moves
  File "C:\Program Files (x86)\Odoo 8.0-20160304\server\.\openerp\tools\misc.py", line 1268, in __setitem__
NotImplementedError: '__setitem__' not supported on frozendict
```

Thanks if you can help me. If not i will try to fix it.

**Comment by hbto** [comment]
@urbandesignec 

Thanks for the report

please make a PR
by updating param
context = dict(context or {})
before
https://github.com/Vauxoo/addons-vauxoo/blob/8.0/account_voucher_no_check_default/account_voucher.py#L72-L74
to defrost dict

Regards
