### ISSUE TITLE
[9.0] cannot install modules

### ISSUE THREAD

**Issue by vasarmilan** [Vauxoo/addons-vauxoo#923]
I've been trying to install website_product_filters module in odoo v9, and whenever it tries to install dependency website_rate_product, it fails with the following log:

2016-05-07 23:31:26,990 22092 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/http.py", line 680, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/http.py", line 309, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/http.py", line 959, in __call__
    return self.method(_args, *_kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/tools/convert.py", line 777, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/tools/convert.py", line 700, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/tools/convert.py", line 782, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/tools/convert.py", line 793, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/addons/base/ir/ir_model.py", line 982, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160415-py2.7.egg/openerp/addons/base/ir/ir_model.py", line 972, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: website.theme" while parsing None:16, near
<data name="Product rating frontend assets" inherit_id="website.theme">
            <xpath expr="//link[@href=&quot;/website/static/src/css/website.css&quot;]" position="after">
                <link href="/website_rate_product/static/src/less/stars.less" rel="stylesheet" type="text/less"/>
            </xpath>
        </data>

any help would be appriciated. i'm pretty new to odoo.

thank you

**Comment by oscarolar** [comment]
this is for version 8 only.

**Comment by nhomar** [comment]
@oscarolar, if this module is illogical in v9.0 please remove it from the v9.0 branch, if it is planned to be migrated, then the issue is valid.
